name: docker build container

on: [push]

permissions:
  contents: read

jobs:
  docker-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          build-options:
            "--build-arg \"GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}\" \
            --build-arg \"GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}\" "
          context: build/docker
          image-repository: senzing-factory/${{ steps.repo-basename.outputs.repo }}
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
